apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webapp
    spec:
      containers:
      - image: 'dtr.local/demo/webapp:'
        name: webapp
        ports:
        - containerPort: 8090
        resources: {}
      restartPolicy: Always
status: {}
